<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Services;

use Dodopayments\Utils\Serializer;
use Dodopayments\Models;

class Brands extends BaseService
{
    public function listBrandsHandler(): Models\ListBrandsResponse
    {
        $data = $this->sendRequest('get', '/brands', []);

        return Serializer::deserialize($data, Models\ListBrandsResponse::class);
    }

    public function createBrandHandler(Models\CreateBrandRequest $input): Models\BrandResponse
    {
        $data = $this->sendRequest('post', '/brands', ['json' => Serializer::serialize($input)]);

        return Serializer::deserialize($data, Models\BrandResponse::class);
    }

    public function getBrandHandler(string $id): Models\BrandResponse
    {
        $data = $this->sendRequest('get', "/brands/{$id}", []);

        return Serializer::deserialize($data, Models\BrandResponse::class);
    }

    public function patchBrandHandler(Models\PatchBrandRequest $input, string $id): Models\BrandResponse
    {
        $data = $this->sendRequest('patch', "/brands/{$id}", ['json' => Serializer::serialize($input)]);

        return Serializer::deserialize($data, Models\BrandResponse::class);
    }

    public function updateBrandImage(string $id): Models\UpdateBrandImageResponse
    {
        $data = $this->sendRequest('put', "/brands/{$id}/images", []);

        return Serializer::deserialize($data, Models\UpdateBrandImageResponse::class);
    }
}
