<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Services;

use Dodopayments\Utils\Serializer;
use Dodopayments\Models;

class CheckoutSessions extends BaseService
{
    public function createSession(Models\CreateCheckoutSessionRequest $input): Models\CreateSessionResponse
    {
        $data = $this->sendRequest('post', '/checkout/sessions', ['json' => Serializer::serialize($input)]);

        return Serializer::deserialize($data, Models\CreateSessionResponse::class);
    }
}
