<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Services;

use Dodopayments\Utils\Serializer;
use Dodopayments\Models;

class Customers extends BaseService
{
    public function listCustomers(int $pageSize = null, int $pageNumber = null): Models\GetCustomersListResponse
    {
        $data = $this->sendRequest('get', '/customers', [
            'query' => [
                'page_size' => $pageSize,
                'page_number' => $pageNumber,
            ],
        ]);

        return Serializer::deserialize($data, Models\GetCustomersListResponse::class);
    }

    public function createCustomer(Models\CreateCustomerRequest $input): Models\CustomerResponse
    {
        $data = $this->sendRequest('post', '/customers', ['json' => Serializer::serialize($input)]);

        return Serializer::deserialize($data, Models\CustomerResponse::class);
    }

    public function getCustomerHandler(string $customerId): Models\CustomerResponse
    {
        $data = $this->sendRequest('get', "/customers/{$customerId}", []);

        return Serializer::deserialize($data, Models\CustomerResponse::class);
    }

    public function patchCustomer(Models\PatchCustomerRequest $input, string $customerId): Models\CustomerResponse
    {
        $data = $this->sendRequest('patch', "/customers/{$customerId}", ['json' => Serializer::serialize($input)]);

        return Serializer::deserialize($data, Models\CustomerResponse::class);
    }

    public function createCustomerPortalSession(string $customerId, bool $sendEmail = null): mixed
    {
        $data = $this->sendRequest('post', "/customers/{$customerId}/customer-portal/session", [
            'query' => [
                'send_email' => $sendEmail,
            ],
        ]);

        return json_decode($data, true);
    }
}
