<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Services;

use Dodopayments\Utils\Serializer;
use Dodopayments\Models;

class Discounts extends BaseService
{
    public function listDiscountsHandler(int $pageSize = null, int $pageNumber = null): Models\GetDiscountsListResponse
    {
        $data = $this->sendRequest('get', '/discounts', [
            'query' => [
                'page_size' => $pageSize,
                'page_number' => $pageNumber,
            ],
        ]);

        return Serializer::deserialize($data, Models\GetDiscountsListResponse::class);
    }

    /**
     * If `code` is omitted or empty, a random 16-char uppercase code is generated.
     */
    public function createDiscountHandler(Models\CreateDiscountRequest $input): Models\DiscountResponse
    {
        $data = $this->sendRequest('post', '/discounts', ['json' => Serializer::serialize($input)]);

        return Serializer::deserialize($data, Models\DiscountResponse::class);
    }

    public function getDiscountHandler(string $discountId): Models\DiscountResponse
    {
        $data = $this->sendRequest('get', "/discounts/{$discountId}", []);

        return Serializer::deserialize($data, Models\DiscountResponse::class);
    }

    public function patchDiscountHandler(
        Models\PatchDiscountRequest $input,
        string $discountId
    ): Models\DiscountResponse {
        $data = $this->sendRequest('patch', "/discounts/{$discountId}", ['json' => Serializer::serialize($input)]);

        return Serializer::deserialize($data, Models\DiscountResponse::class);
    }

    public function deleteDiscountHandler(string $discountId): mixed
    {
        $data = $this->sendRequest('delete', "/discounts/{$discountId}", []);

        return json_decode($data, true);
    }
}
