<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Services;

use Dodopayments\Utils\Serializer;
use Dodopayments\Models;

class Disputes extends BaseService
{
    public function listDisputes(
        string $createdAtGte = null,
        string $createdAtLte = null,
        int $pageSize = null,
        int $pageNumber = null,
        Models\DisputeStatus $disputeStatus = null,
        Models\DisputeStage $disputeStage = null,
        string $customerId = null
    ): Models\GetDisputesListResponse {
        $data = $this->sendRequest('get', '/disputes', [
            'query' => [
                'created_at_gte' => $createdAtGte,
                'created_at_lte' => $createdAtLte,
                'page_size' => $pageSize,
                'page_number' => $pageNumber,
                'dispute_status' => $disputeStatus,
                'dispute_stage' => $disputeStage,
                'customer_id' => $customerId,
            ],
        ]);

        return Serializer::deserialize($data, Models\GetDisputesListResponse::class);
    }

    public function getDisputeHandler(string $disputeId): Models\DisputeResponse
    {
        $data = $this->sendRequest('get', "/disputes/{$disputeId}", []);

        return Serializer::deserialize($data, Models\DisputeResponse::class);
    }
}
