<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Services;

use Dodopayments\Utils\Serializer;
use Dodopayments\Models;

class Invoices extends BaseService
{
    public function getPaymentInvoiceNoAuth(string $paymentId): array
    {
        $data = $this->sendRequest('get', "/invoices/payments/{$paymentId}", []);

        return json_decode($data, true);
    }
}
