<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Services;

use Dodopayments\Utils\Serializer;
use Dodopayments\Models;

class Licenses extends BaseService
{
    public function activateLicenseKey(Models\ActivateLicenseKeyRequest $input): Models\LicenseKeyInstanceResponse
    {
        $data = $this->sendRequest('post', '/licenses/activate', ['json' => Serializer::serialize($input)]);

        return Serializer::deserialize($data, Models\LicenseKeyInstanceResponse::class);
    }

    public function deactivateLicenseKey(Models\DeactivateLicenseKeyRequest $input): mixed
    {
        $data = $this->sendRequest('post', '/licenses/deactivate', ['json' => Serializer::serialize($input)]);

        return json_decode($data, true);
    }

    public function validateLicenseKey(Models\ValidateLicenseKeyRequest $input): Models\ValidateLicenseKeyResponse
    {
        $data = $this->sendRequest('post', '/licenses/validate', ['json' => Serializer::serialize($input)]);

        return Serializer::deserialize($data, Models\ValidateLicenseKeyResponse::class);
    }
}
