<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Services;

use Dodopayments\Utils\Serializer;
use Dodopayments\Models;

class Meters extends BaseService
{
    public function listMetersHandler(int $pageSize = null, int $pageNumber = null): Models\ListMetersResponse
    {
        $data = $this->sendRequest('get', '/meters', [
            'query' => [
                'page_size' => $pageSize,
                'page_number' => $pageNumber,
            ],
        ]);

        return Serializer::deserialize($data, Models\ListMetersResponse::class);
    }

    public function createMeter(Models\CreateMeterRequest $input): Models\MeterResponse
    {
        $data = $this->sendRequest('post', '/meters', ['json' => Serializer::serialize($input)]);

        return Serializer::deserialize($data, Models\MeterResponse::class);
    }

    public function getMeterHandler(string $id): Models\MeterResponse
    {
        $data = $this->sendRequest('get', "/meters/{$id}", []);

        return Serializer::deserialize($data, Models\MeterResponse::class);
    }

    public function deleteMeter(string $id): mixed
    {
        $data = $this->sendRequest('delete', "/meters/{$id}", []);

        return json_decode($data, true);
    }

    public function unarchiveMeter(string $id): mixed
    {
        $data = $this->sendRequest('post', "/meters/{$id}/unarchive", []);

        return json_decode($data, true);
    }
}
