<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Services;

use Dodopayments\Utils\Serializer;
use Dodopayments\Models;

class OutgoingWebhooks extends BaseService
{
    public function dummyHandlerForOutgoingWebhookDocs(
        Models\OutgoingWebhook $input,
        string $webhookId,
        string $webhookSignature,
        string $webhookTimestamp
    ): mixed {
        $data = $this->sendRequest('post', '/your-webhook-url', [
            'json' => Serializer::serialize($input),
            'headers' => [
                'webhook-id' => $webhookId,
                'webhook-signature' => $webhookSignature,
                'webhook-timestamp' => $webhookTimestamp,
            ],
        ]);

        return json_decode($data, true);
    }
}
