<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Services;

use Dodopayments\Utils\Serializer;
use Dodopayments\Models;

class Payments extends BaseService
{
    public function listPaymentsHandler(
        string $createdAtGte = null,
        string $createdAtLte = null,
        int $pageSize = null,
        int $pageNumber = null,
        string $customerId = null,
        Models\IntentStatus $status = null
    ): Models\GetPaymentsListResponse {
        $data = $this->sendRequest('get', '/payments', [
            'query' => [
                'created_at_gte' => $createdAtGte,
                'created_at_lte' => $createdAtLte,
                'page_size' => $pageSize,
                'page_number' => $pageNumber,
                'customer_id' => $customerId,
                'status' => $status,
            ],
        ]);

        return Serializer::deserialize($data, Models\GetPaymentsListResponse::class);
    }

    public function createOneTimePaymentHandler(
        Models\CreateOneTimePaymentRequest $input
    ): Models\CreateOneTimePaymentResponse {
        $data = $this->sendRequest('post', '/payments', ['json' => Serializer::serialize($input)]);

        return Serializer::deserialize($data, Models\CreateOneTimePaymentResponse::class);
    }

    public function getPaymentHandler(string $paymentId): Models\PaymentResponse
    {
        $data = $this->sendRequest('get', "/payments/{$paymentId}", []);

        return Serializer::deserialize($data, Models\PaymentResponse::class);
    }
}
