<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Services;

use Dodopayments\Utils\Serializer;
use Dodopayments\Models;

class Refunds extends BaseService
{
    public function listRefunds(
        string $createdAtGte = null,
        string $createdAtLte = null,
        int $pageSize = null,
        int $pageNumber = null,
        Models\RefundStatus $status = null,
        string $customerId = null
    ): Models\GetRefundsListResponse {
        $data = $this->sendRequest('get', '/refunds', [
            'query' => [
                'created_at_gte' => $createdAtGte,
                'created_at_lte' => $createdAtLte,
                'page_size' => $pageSize,
                'page_number' => $pageNumber,
                'status' => $status,
                'customer_id' => $customerId,
            ],
        ]);

        return Serializer::deserialize($data, Models\GetRefundsListResponse::class);
    }

    public function createRefundHandler(Models\CreateRefundRequest $input): Models\RefundResponse
    {
        $data = $this->sendRequest('post', '/refunds', ['json' => Serializer::serialize($input)]);

        return Serializer::deserialize($data, Models\RefundResponse::class);
    }

    public function getRefundHandler(string $refundId): Models\RefundResponse
    {
        $data = $this->sendRequest('get', "/refunds/{$refundId}", []);

        return Serializer::deserialize($data, Models\RefundResponse::class);
    }
}
