<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Services;

use Dodopayments\Utils\Serializer;
use Dodopayments\Models;

class WebhookEvents extends BaseService
{
    public function listWebhookEvents(
        string $createdAtGte = null,
        string $createdAtLte = null,
        int $limit = null,
        string $objectId = null,
        int $pageSize = null,
        int $pageNumber = null
    ): Models\ListWebhookEventsResponse {
        $data = $this->sendRequest('get', '/webhook_events', [
            'query' => [
                'created_at_gte' => $createdAtGte,
                'created_at_lte' => $createdAtLte,
                'limit' => $limit,
                'object_id' => $objectId,
                'page_size' => $pageSize,
                'page_number' => $pageNumber,
            ],
        ]);

        return Serializer::deserialize($data, Models\ListWebhookEventsResponse::class);
    }

    public function getWebhookEvent(string $webhookEventId): Models\WebhookEventLogResponse
    {
        $data = $this->sendRequest('get', "/webhook_events/{$webhookEventId}", []);

        return Serializer::deserialize($data, Models\WebhookEventLogResponse::class);
    }
}
