<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class ActivateLicenseKeyRequest
{
    #[SerializedName('license_key')]
    public string $licenseKey;

    #[SerializedName('name')]
    public string $name;

    public function __construct(string $licenseKey, string $name)
    {
        $this->licenseKey = $licenseKey;
        $this->name = $name;
    }
}
