<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

enum AggregationType: string
{
    case Count = 'count';
    case Sum = 'sum';
    case UniqueCount = 'unique_count';
    case Max = 'max';
    case Last = 'last';
}
