<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class AttachExistingCustomer
{
    #[SerializedName('customer_id')]
    public string $customerId;

    public function __construct(string $customerId)
    {
        $this->customerId = $customerId;
    }
}
