<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class BillingAddress
{
    /**
     * City name
     */
    #[SerializedName('city')]
    public string $city;

    /**
     * ISO country code alpha2 variant
     */
    #[SerializedName('country')]
    public CountryCodeAlpha2 $country;

    /**
     * State or province name
     */
    #[SerializedName('state')]
    public string $state;

    /**
     * Street address including house number and unit/apartment if applicable
     */
    #[SerializedName('street')]
    public string $street;

    /**
     * Postal code or ZIP code
     */
    #[SerializedName('zipcode')]
    public string $zipcode;

    public function __construct(
        string $city,
        CountryCodeAlpha2 $country,
        string $state,
        string $street,
        string $zipcode
    ) {
        $this->city = $city;
        $this->country = $country;
        $this->state = $state;
        $this->street = $street;
        $this->zipcode = $zipcode;
    }
}
