<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

enum BrandVerificationStatus: string
{
    case Success = 'Success';
    case Fail = 'Fail';
    case Review = 'Review';
    case Hold = 'Hold';
}
