<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class BrandResponse
{
    #[SerializedName('brand_id')]
    public string $brandId;

    #[SerializedName('business_id')]
    public string $businessId;

    #[SerializedName('description')]
    public ?string $description;

    #[SerializedName('enabled')]
    public bool $enabled;

    #[SerializedName('image')]
    public ?string $image;

    #[SerializedName('name')]
    public ?string $name;

    /**
     * Incase the brand verification fails or is put on hold
     */
    #[SerializedName('reason_for_hold')]
    public ?string $reasonForHold;

    #[SerializedName('statement_descriptor')]
    public string $statementDescriptor;

    #[SerializedName('support_email')]
    public ?string $supportEmail;

    #[SerializedName('url')]
    public ?string $url;

    #[SerializedName('verification_enabled')]
    public bool $verificationEnabled;

    #[SerializedName('verification_status')]
    public BrandVerificationStatus $verificationStatus;

    public function __construct(
        string $brandId,
        string $businessId,
        ?string $description = null,
        bool $enabled,
        ?string $image = null,
        ?string $name = null,
        ?string $reasonForHold = null,
        string $statementDescriptor,
        ?string $supportEmail = null,
        ?string $url = null,
        bool $verificationEnabled,
        BrandVerificationStatus $verificationStatus
    ) {
        $this->brandId = $brandId;
        $this->businessId = $businessId;
        $this->description = $description;
        $this->enabled = $enabled;
        $this->image = $image;
        $this->name = $name;
        $this->reasonForHold = $reasonForHold;
        $this->statementDescriptor = $statementDescriptor;
        $this->supportEmail = $supportEmail;
        $this->url = $url;
        $this->verificationEnabled = $verificationEnabled;
        $this->verificationStatus = $verificationStatus;
    }
}
