<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class CheckoutSessionCustomization
{
    /**
     * Show on demand tag
     */
    #[SerializedName('show_on_demand_tag')]
    public ?bool $showOnDemandTag;

    /**
     * Show order details by default
     */
    #[SerializedName('show_order_details')]
    public ?bool $showOrderDetails;

    #[SerializedName('theme')]
    public ?CheckoutTheme $theme;

    public function __construct(
        ?bool $showOnDemandTag = null,
        ?bool $showOrderDetails = null,
        ?CheckoutTheme $theme = null
    ) {
        $this->showOnDemandTag = $showOnDemandTag;
        $this->showOrderDetails = $showOrderDetails;
        $this->theme = $theme;
    }
}
