<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class CheckoutSessionFlags
{
    /**
	 * if customer is allowed to change currency, set it to true

Default is true
	 */
    #[SerializedName('allow_currency_selection')]
    public ?bool $allowCurrencySelection;

    /**
	 * If the customer is allowed to apply discount code, set it to true.

Default is true
	 */
    #[SerializedName('allow_discount_code')]
    public ?bool $allowDiscountCode;

    /**
	 * If phone number is collected from customer, set it to rue

Default is true
	 */
    #[SerializedName('allow_phone_number_collection')]
    public ?bool $allowPhoneNumberCollection;

    /**
	 * If the customer is allowed to add tax id, set it to true

Default is true
	 */
    #[SerializedName('allow_tax_id')]
    public ?bool $allowTaxId;

    /**
	 * Set to true if a new customer object should be created.
By default email is used to find an existing customer to attach the session to

Default is false
	 */
    #[SerializedName('always_create_new_customer')]
    public ?bool $alwaysCreateNewCustomer;

    public function __construct(
        ?bool $allowCurrencySelection = null,
        ?bool $allowDiscountCode = null,
        ?bool $allowPhoneNumberCollection = null,
        ?bool $allowTaxId = null,
        ?bool $alwaysCreateNewCustomer = null
    ) {
        $this->allowCurrencySelection = $allowCurrencySelection;
        $this->allowDiscountCode = $allowDiscountCode;
        $this->allowPhoneNumberCollection = $allowPhoneNumberCollection;
        $this->allowTaxId = $allowTaxId;
        $this->alwaysCreateNewCustomer = $alwaysCreateNewCustomer;
    }
}
