<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

enum Conjunction: string
{
    case And_ = 'and';
    case Or_ = 'or';
}
