<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class CreateSubscriptionChargeResponse
{
    #[SerializedName('payment_id')]
    public string $paymentId;

    public function __construct(string $paymentId)
    {
        $this->paymentId = $paymentId;
    }
}
