<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class CreateCheckoutSessionRequest
{
    /**
	 * If all the data is available at session create time and auto_confirm is true,
directly redirect to payment
	 */
    #[SerializedName('auto_confirm')]
    public ?bool $autoConfirm;

    #[SerializedName('billing_address')]
    public ?CreateCheckoutSessionRequestBillingAddress $billingAddress;

    #[SerializedName('billing_currency')]
    public ?CreateCheckoutSessionRequestBillingCurrency $billingCurrency;

    #[SerializedName('customer')]
    public ?Customer $customer;

    #[SerializedName('customization')]
    public ?CheckoutSessionCustomization $customization;

    #[SerializedName('discount_code')]
    public ?string $discountCode;

    #[SerializedName('feature_flags')]
    public CheckoutSessionFlags $featureFlags;

    #[SerializedName('metadata')]
    public ?CreateCheckoutSessionRequestMetadata $metadata;

    /**
     * @var ProductItemReq[]
     */
    #[SerializedName('product_cart')]
    public array $productCart;

    #[SerializedName('return_url')]
    public ?string $returnUrl;

    /**
     * Display saved payment methods of a returning customer False by default
     */
    #[SerializedName('show_saved_payment_methods')]
    public ?bool $showSavedPaymentMethods;

    #[SerializedName('subscription_data')]
    public ?CreateCheckoutSessionRequestSubscriptionData $subscriptionData;

    /**
     * Tax ID in case the payment is B2B. If tax id validation fails the payment creation will fail
     */
    #[SerializedName('tax_id')]
    public ?string $taxId;

    public function __construct(
        ?bool $autoConfirm = null,
        ?CreateCheckoutSessionRequestBillingAddress $billingAddress = null,
        ?CreateCheckoutSessionRequestBillingCurrency $billingCurrency = null,
        ?Customer $customer = null,
        ?CheckoutSessionCustomization $customization = null,
        ?string $discountCode = null,
        CheckoutSessionFlags $featureFlags,
        ?CreateCheckoutSessionRequestMetadata $metadata = null,
        array $productCart,
        ?string $returnUrl = null,
        ?bool $showSavedPaymentMethods = null,
        ?CreateCheckoutSessionRequestSubscriptionData $subscriptionData = null,
        ?string $taxId = null
    ) {
        $this->autoConfirm = $autoConfirm;
        $this->billingAddress = $billingAddress;
        $this->billingCurrency = $billingCurrency;
        $this->customer = $customer;
        $this->customization = $customization;
        $this->discountCode = $discountCode;
        $this->featureFlags = $featureFlags;
        $this->metadata = $metadata;
        $this->productCart = $productCart;
        $this->returnUrl = $returnUrl;
        $this->showSavedPaymentMethods = $showSavedPaymentMethods;
        $this->subscriptionData = $subscriptionData;
        $this->taxId = $taxId;
    }
}
