<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class CreateDigitalProductDeliveryRequest
{
    /**
     * External URL to digital product
     */
    #[SerializedName('external_url')]
    public ?string $externalUrl;

    /**
     * Instructions to download and use the digital product
     */
    #[SerializedName('instructions')]
    public ?string $instructions;

    public function __construct(?string $externalUrl = null, ?string $instructions = null)
    {
        $this->externalUrl = $externalUrl;
        $this->instructions = $instructions;
    }
}
