<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class CreateAddonRequest
{
    #[SerializedName('currency')]
    public Currency $currency;

    /**
     * Optional description of the Addon
     */
    #[SerializedName('description')]
    public ?string $description;

    /**
     * Name of the Addon
     */
    #[SerializedName('name')]
    public string $name;

    /**
     * Amount of the addon
     */
    #[SerializedName('price')]
    public int $price;

    /**
     * Represents the different categories of taxation applicable to various products and services.
     */
    #[SerializedName('tax_category')]
    public TaxCategory $taxCategory;

    public function __construct(
        Currency $currency,
        ?string $description = null,
        string $name,
        int $price,
        TaxCategory $taxCategory
    ) {
        $this->currency = $currency;
        $this->description = $description;
        $this->name = $name;
        $this->price = $price;
        $this->taxCategory = $taxCategory;
    }
}
