<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class CreateProductRequest
{
    /**
     * @var string[]|null
     * Addons available for subscription product
     */
    #[SerializedName('addons')]
    public ?array $addons;

    /**
     * Optional description of the product
     */
    #[SerializedName('description')]
    public ?string $description;

    /**
     * Optional message displayed during license key activation
     */
    #[SerializedName('license_key_activation_message')]
    public ?string $licenseKeyActivationMessage;

    /**
	 * The number of times the license key can be activated.
Must be 0 or greater
	 */
    #[SerializedName('license_key_activations_limit')]
    public ?int $licenseKeyActivationsLimit;

    #[SerializedName('license_key_duration')]
    public ?LicenseKeyDuration $licenseKeyDuration;

    /**
	 * When true, generates and sends a license key to your customer.
Defaults to false
	 */
    #[SerializedName('license_key_enabled')]
    public ?bool $licenseKeyEnabled;

    /**
     * Optional name of the product
     */
    #[SerializedName('name')]
    public ?string $name;

    #[SerializedName('price')]
    public Price $price;

    /**
     * Represents the different categories of taxation applicable to various products and services.
     */
    #[SerializedName('tax_category')]
    public TaxCategory $taxCategory;

    public function __construct(
        ?array $addons = [],
        ?string $description = null,
        ?string $licenseKeyActivationMessage = null,
        ?int $licenseKeyActivationsLimit = null,
        ?LicenseKeyDuration $licenseKeyDuration = null,
        ?bool $licenseKeyEnabled = null,
        ?string $name = null,
        Price $price,
        TaxCategory $taxCategory
    ) {
        $this->addons = $addons;
        $this->description = $description;
        $this->licenseKeyActivationMessage = $licenseKeyActivationMessage;
        $this->licenseKeyActivationsLimit = $licenseKeyActivationsLimit;
        $this->licenseKeyDuration = $licenseKeyDuration;
        $this->licenseKeyEnabled = $licenseKeyEnabled;
        $this->name = $name;
        $this->price = $price;
        $this->taxCategory = $taxCategory;
    }
}
