<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class CreateWebhookRequest
{
    /**
	 * Filter events to the webhook.

Webhook event will only be sent for events in the list.
	 */
    #[SerializedName('description')]
    public ?string $description;

    /**
	 * Create the webhook in a disabled state.

Default is false
	 */
    #[SerializedName('disabled')]
    public ?bool $disabled;

    /**
     * @var EventType[]|null
     */
    #[SerializedName('filter_types')]
    public ?array $filterTypes;

    #[SerializedName('headers')]
    public ?array $headers;

    /**
     * The request's idempotency key
     */
    #[SerializedName('idempotency_key')]
    public ?string $idempotencyKey;

    #[SerializedName('metadata')]
    public ?array $metadata;

    #[SerializedName('rate_limit')]
    public ?int $rateLimit;

    /**
     * Url of the webhook
     */
    #[SerializedName('url')]
    public string $url;

    public function __construct(
        ?string $description = null,
        ?bool $disabled = null,
        ?array $filterTypes = [],
        ?array $headers = [],
        ?string $idempotencyKey = null,
        ?array $metadata = [],
        ?int $rateLimit = null,
        string $url
    ) {
        $this->description = $description;
        $this->disabled = $disabled;
        $this->filterTypes = $filterTypes;
        $this->headers = $headers;
        $this->idempotencyKey = $idempotencyKey;
        $this->metadata = $metadata;
        $this->rateLimit = $rateLimit;
        $this->url = $url;
    }
}
