<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class CreateBrandRequest
{
    #[SerializedName('description')]
    public ?string $description;

    #[SerializedName('name')]
    public ?string $name;

    #[SerializedName('statement_descriptor')]
    public ?string $statementDescriptor;

    #[SerializedName('support_email')]
    public ?string $supportEmail;

    #[SerializedName('url')]
    public ?string $url;

    public function __construct(
        ?string $description = null,
        ?string $name = null,
        ?string $statementDescriptor = null,
        ?string $supportEmail = null,
        ?string $url = null
    ) {
        $this->description = $description;
        $this->name = $name;
        $this->statementDescriptor = $statementDescriptor;
        $this->supportEmail = $supportEmail;
        $this->url = $url;
    }
}
