<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class CreateMeterRequest
{
    #[SerializedName('aggregation_type')]
    public AggregationType $aggregationType;

    /**
     * Optional description of the meter
     */
    #[SerializedName('description')]
    public ?string $description;

    /**
     * Event type to track
     */
    #[SerializedName('event_type')]
    public string $eventType;

    /**
	 * JsonPath expression for event value (e.g., "$.metadata.tokens")
Required when aggregation_type is not COUNT
	 */
    #[SerializedName('event_value')]
    public ?string $eventValue;

    #[SerializedName('filter')]
    public ?CreateMeterRequestFilter $filter;

    /**
     * measurement unit
     */
    #[SerializedName('measurement_unit')]
    public string $measurementUnit;

    /**
     * Name of the meter
     */
    #[SerializedName('name')]
    public string $name;

    public function __construct(
        AggregationType $aggregationType,
        ?string $description = null,
        string $eventType,
        ?string $eventValue = null,
        ?CreateMeterRequestFilter $filter = null,
        string $measurementUnit,
        string $name
    ) {
        $this->aggregationType = $aggregationType;
        $this->description = $description;
        $this->eventType = $eventType;
        $this->eventValue = $eventValue;
        $this->filter = $filter;
        $this->measurementUnit = $measurementUnit;
        $this->name = $name;
    }
}
