<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class CreateSubscriptionChargeRequest
{
    #[SerializedName('product_price')]
    public int $productPrice;

    public function __construct(int $productPrice)
    {
        $this->productPrice = $productPrice;
    }
}
