<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

/**
 * Request payload for creating a new subscription

This struct represents the data required to create a new subscription in the system.
It includes details about the product, quantity, customer information, and billing details.
 */
class CreateSubscriptionRequest
{
    #[SerializedName('billing')]
    public BillingAddress $billing;

    #[SerializedName('customer')]
    public CustomerRequest $customer;

    #[SerializedName('metadata')]
    public ?array $metadata;

    /**
	 * If true, generates a payment link.
Defaults to false if not specified.
	 */
    #[SerializedName('payment_link')]
    public ?bool $paymentLink;

    /**
     * Unique identifier of the product to subscribe to
     */
    #[SerializedName('product_id')]
    public string $productId;

    /**
     * Number of units to subscribe for. Must be at least 1.
     */
    #[SerializedName('quantity')]
    public int $quantity;

    /**
     * Optional URL to redirect after successful subscription creation
     */
    #[SerializedName('return_url')]
    public ?string $returnUrl;

    /**
     * Tax ID in case the payment is B2B. If tax id validation fails the payment creation will fail
     */
    #[SerializedName('tax_id')]
    public ?string $taxId;

    /**
	 * Optional trial period in days
If specified, this value overrides the trial period set in the product's price
Must be between 0 and 10000 days
	 */
    #[SerializedName('trial_period_days')]
    public ?int $trialPeriodDays;

    public function __construct(
        BillingAddress $billing,
        CustomerRequest $customer,
        ?array $metadata = [],
        ?bool $paymentLink = null,
        string $productId,
        int $quantity,
        ?string $returnUrl = null,
        ?string $taxId = null,
        ?int $trialPeriodDays = null
    ) {
        $this->billing = $billing;
        $this->customer = $customer;
        $this->metadata = $metadata;
        $this->paymentLink = $paymentLink;
        $this->productId = $productId;
        $this->quantity = $quantity;
        $this->returnUrl = $returnUrl;
        $this->taxId = $taxId;
        $this->trialPeriodDays = $trialPeriodDays;
    }
}
