<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class CreateNewCustomer
{
    /**
	 * When true, the most recently created customer object with the given email is used if exists.
False by default
	 */
    #[SerializedName('create_new_customer')]
    public ?bool $createNewCustomer;

    #[SerializedName('email')]
    public string $email;

    #[SerializedName('name')]
    public string $name;

    #[SerializedName('phone_number')]
    public ?string $phoneNumber;

    public function __construct(
        ?bool $createNewCustomer = null,
        string $email,
        string $name,
        ?string $phoneNumber = null
    ) {
        $this->createNewCustomer = $createNewCustomer;
        $this->email = $email;
        $this->name = $name;
        $this->phoneNumber = $phoneNumber;
    }
}
