<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class CreateOneTimePaymentResponse
{
    /**
	 * Client secret used to load Dodo checkout SDK
NOTE : Dodo checkout SDK will be coming soon
	 */
    #[SerializedName('client_secret')]
    public string $clientSecret;

    #[SerializedName('customer')]
    public CustomerLimitedDetailsResponse $customer;

    #[SerializedName('metadata')]
    public array $metadata;

    /**
     * Unique identifier for the payment
     */
    #[SerializedName('payment_id')]
    public string $paymentId;

    /**
     * Optional URL to a hosted payment page
     */
    #[SerializedName('payment_link')]
    public ?string $paymentLink;

    /**
     * @var OneTimeProductCartItemReq[]|null
     * Optional list of products included in the payment
     */
    #[SerializedName('product_cart')]
    public ?array $productCart;

    /**
     * Total amount of the payment in smallest currency unit (e.g. cents)
     */
    #[SerializedName('total_amount')]
    public int $totalAmount;

    public function __construct(
        string $clientSecret,
        CustomerLimitedDetailsResponse $customer,
        array $metadata,
        string $paymentId,
        ?string $paymentLink = null,
        ?array $productCart = [],
        int $totalAmount
    ) {
        $this->clientSecret = $clientSecret;
        $this->customer = $customer;
        $this->metadata = $metadata;
        $this->paymentId = $paymentId;
        $this->paymentLink = $paymentLink;
        $this->productCart = $productCart;
        $this->totalAmount = $totalAmount;
    }
}
