<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class CreateSessionResponse
{
    /**
     * Checkout url
     */
    #[SerializedName('checkout_url')]
    public string $checkoutUrl;

    /**
     * The ID of the created checkout session
     */
    #[SerializedName('session_id')]
    public string $sessionId;

    public function __construct(string $checkoutUrl, string $sessionId)
    {
        $this->checkoutUrl = $checkoutUrl;
        $this->sessionId = $sessionId;
    }
}
