<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class CreateSubscriptionChargeRequest
{
    #[SerializedName('metadata')]
    public ?array $metadata;

    /**
	 * The product price. Represented in the lowest denomination of the currency (e.g., cents for USD).
For example, to charge $1.00, pass `100`.
	 */
    #[SerializedName('product_price')]
    public int $productPrice;

    public function __construct(?array $metadata = [], int $productPrice)
    {
        $this->metadata = $metadata;
        $this->productPrice = $productPrice;
    }
}
