<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class CustomerLimitedDetailsResponse
{
    /**
     * Unique identifier for the customer
     */
    #[SerializedName('customer_id')]
    public string $customerId;

    /**
     * Email address of the customer
     */
    #[SerializedName('email')]
    public string $email;

    /**
     * Full name of the customer
     */
    #[SerializedName('name')]
    public string $name;

    public function __construct(string $customerId, string $email, string $name)
    {
        $this->customerId = $customerId;
        $this->email = $email;
        $this->name = $name;
    }
}
