<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class CustomerResponse
{
    #[SerializedName('business_id')]
    public string $businessId;

    #[SerializedName('created_at')]
    public string $createdAt;

    #[SerializedName('customer_id')]
    public string $customerId;

    #[SerializedName('email')]
    public string $email;

    #[SerializedName('name')]
    public string $name;

    #[SerializedName('phone_number')]
    public ?string $phoneNumber;

    public function __construct(
        string $businessId,
        string $createdAt,
        string $customerId,
        string $email,
        string $name,
        ?string $phoneNumber = null
    ) {
        $this->businessId = $businessId;
        $this->createdAt = $createdAt;
        $this->customerId = $customerId;
        $this->email = $email;
        $this->name = $name;
        $this->phoneNumber = $phoneNumber;
    }
}
