<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class DigitalProductDeliveryFile
{
    #[SerializedName('file_id')]
    public string $fileId;

    #[SerializedName('file_name')]
    public string $fileName;

    #[SerializedName('url')]
    public string $url;

    public function __construct(string $fileId, string $fileName, string $url)
    {
        $this->fileId = $fileId;
        $this->fileName = $fileName;
        $this->url = $url;
    }
}
