<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class DisableOnDemandReq
{
    #[SerializedName('next_billing_date')]
    public string $nextBillingDate;

    public function __construct(string $nextBillingDate)
    {
        $this->nextBillingDate = $nextBillingDate;
    }
}
