<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

enum DisputeStatus: string
{
    case DisputeOpened = 'dispute_opened';
    case DisputeExpired = 'dispute_expired';
    case DisputeAccepted = 'dispute_accepted';
    case DisputeCancelled = 'dispute_cancelled';
    case DisputeChallenged = 'dispute_challenged';
    case DisputeWon = 'dispute_won';
    case DisputeLost = 'dispute_lost';
}
