<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

/**
 * Event types for Dodo events
 */
enum EventType: string
{
    case PaymentSucceeded = 'payment.succeeded';
    case PaymentFailed = 'payment.failed';
    case PaymentProcessing = 'payment.processing';
    case PaymentCancelled = 'payment.cancelled';
    case RefundSucceeded = 'refund.succeeded';
    case RefundFailed = 'refund.failed';
    case DisputeOpened = 'dispute.opened';
    case DisputeExpired = 'dispute.expired';
    case DisputeAccepted = 'dispute.accepted';
    case DisputeCancelled = 'dispute.cancelled';
    case DisputeChallenged = 'dispute.challenged';
    case DisputeWon = 'dispute.won';
    case DisputeLost = 'dispute.lost';
    case SubscriptionActive = 'subscription.active';
    case SubscriptionRenewed = 'subscription.renewed';
    case SubscriptionOnHold = 'subscription.on_hold';
    case SubscriptionPaused = 'subscription.paused';
    case SubscriptionCancelled = 'subscription.cancelled';
    case SubscriptionFailed = 'subscription.failed';
    case SubscriptionExpired = 'subscription.expired';
    case SubscriptionPlanChanged = 'subscription.plan_changed';
    case LicenseKeyCreated = 'license_key.created';
}
