<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

enum FilterOperator: string
{
    case Equals = 'equals';
    case NotEquals = 'not_equals';
    case GreaterThan = 'greater_than';
    case GreaterThanOrEquals = 'greater_than_or_equals';
    case LessThan = 'less_than';
    case LessThanOrEquals = 'less_than_or_equals';
    case Contains = 'contains';
    case DoesNotContain = 'does_not_contain';
}
