<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class GetPaymentsListResponseItem
{
    #[SerializedName('created_at')]
    public string $createdAt;

    #[SerializedName('currency')]
    public Currency $currency;

    #[SerializedName('customer')]
    public CustomerLimitedDetailsResponse $customer;

    #[SerializedName('metadata')]
    public array $metadata;

    #[SerializedName('payment_id')]
    public string $paymentId;

    #[SerializedName('payment_method')]
    public ?string $paymentMethod;

    #[SerializedName('payment_method_type')]
    public ?string $paymentMethodType;

    #[SerializedName('status')]
    public ?IntentStatus $status;

    #[SerializedName('subscription_id')]
    public ?string $subscriptionId;

    #[SerializedName('total_amount')]
    public int $totalAmount;

    public function __construct(
        string $createdAt,
        Currency $currency,
        CustomerLimitedDetailsResponse $customer,
        array $metadata,
        string $paymentId,
        ?string $paymentMethod = null,
        ?string $paymentMethodType = null,
        ?IntentStatus $status = null,
        ?string $subscriptionId = null,
        int $totalAmount
    ) {
        $this->createdAt = $createdAt;
        $this->currency = $currency;
        $this->customer = $customer;
        $this->metadata = $metadata;
        $this->paymentId = $paymentId;
        $this->paymentMethod = $paymentMethod;
        $this->paymentMethodType = $paymentMethodType;
        $this->status = $status;
        $this->subscriptionId = $subscriptionId;
        $this->totalAmount = $totalAmount;
    }
}
