<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class GetProductResponse
{
    /**
     * @var string[]|null
     * Available Addons for subscription products
     */
    #[SerializedName('addons')]
    public ?array $addons;

    #[SerializedName('brand_id')]
    public string $brandId;

    /**
     * Unique identifier for the business to which the product belongs.
     */
    #[SerializedName('business_id')]
    public string $businessId;

    /**
     * Timestamp when the product was created.
     */
    #[SerializedName('created_at')]
    public string $createdAt;

    /**
     * Description of the product, optional.
     */
    #[SerializedName('description')]
    public ?string $description;

    #[SerializedName('digital_product_delivery')]
    public ?GetProductResponseDigitalProductDelivery $digitalProductDelivery;

    /**
     * URL of the product image, optional.
     */
    #[SerializedName('image')]
    public ?string $image;

    /**
     * Indicates if the product is recurring (e.g., subscriptions).
     */
    #[SerializedName('is_recurring')]
    public bool $isRecurring;

    /**
     * Message sent upon license key activation, if applicable.
     */
    #[SerializedName('license_key_activation_message')]
    public ?string $licenseKeyActivationMessage;

    /**
     * Limit on the number of activations for the license key, if enabled.
     */
    #[SerializedName('license_key_activations_limit')]
    public ?int $licenseKeyActivationsLimit;

    #[SerializedName('license_key_duration')]
    public ?GetProductResponseLicenseKeyDuration $licenseKeyDuration;

    /**
     * Indicates whether the product requires a license key.
     */
    #[SerializedName('license_key_enabled')]
    public bool $licenseKeyEnabled;

    #[SerializedName('metadata')]
    public array $metadata;

    /**
     * Name of the product, optional.
     */
    #[SerializedName('name')]
    public ?string $name;

    #[SerializedName('price')]
    public Price $price;

    /**
     * Unique identifier for the product.
     */
    #[SerializedName('product_id')]
    public string $productId;

    /**
     * Represents the different categories of taxation applicable to various products and services.
     */
    #[SerializedName('tax_category')]
    public TaxCategory $taxCategory;

    /**
     * Timestamp when the product was last updated.
     */
    #[SerializedName('updated_at')]
    public string $updatedAt;

    public function __construct(
        ?array $addons = [],
        string $brandId,
        string $businessId,
        string $createdAt,
        ?string $description = null,
        ?GetProductResponseDigitalProductDelivery $digitalProductDelivery = null,
        ?string $image = null,
        bool $isRecurring,
        ?string $licenseKeyActivationMessage = null,
        ?int $licenseKeyActivationsLimit = null,
        ?GetProductResponseLicenseKeyDuration $licenseKeyDuration = null,
        bool $licenseKeyEnabled,
        array $metadata,
        ?string $name = null,
        Price $price,
        string $productId,
        TaxCategory $taxCategory,
        string $updatedAt
    ) {
        $this->addons = $addons;
        $this->brandId = $brandId;
        $this->businessId = $businessId;
        $this->createdAt = $createdAt;
        $this->description = $description;
        $this->digitalProductDelivery = $digitalProductDelivery;
        $this->image = $image;
        $this->isRecurring = $isRecurring;
        $this->licenseKeyActivationMessage = $licenseKeyActivationMessage;
        $this->licenseKeyActivationsLimit = $licenseKeyActivationsLimit;
        $this->licenseKeyDuration = $licenseKeyDuration;
        $this->licenseKeyEnabled = $licenseKeyEnabled;
        $this->metadata = $metadata;
        $this->name = $name;
        $this->price = $price;
        $this->productId = $productId;
        $this->taxCategory = $taxCategory;
        $this->updatedAt = $updatedAt;
    }
}
