<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

/**
 * The value of the headers is returned in the `headers` field.

Sensitive headers that have been redacted are returned in the sensitive
field.
 */
class GetWebhookHeadersResponse
{
    #[SerializedName('headers')]
    public array $headers;

    /**
     * @var string[]
     * Sensitive headers without the value
     */
    #[SerializedName('sensitive')]
    public array $sensitive;

    public function __construct(array $headers, array $sensitive)
    {
        $this->headers = $headers;
        $this->sensitive = $sensitive;
    }
}
