<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class LicenseKeyInstanceResponse
{
    #[SerializedName('business_id')]
    public string $businessId;

    #[SerializedName('created_at')]
    public string $createdAt;

    #[SerializedName('id')]
    public string $id;

    #[SerializedName('license_key_id')]
    public string $licenseKeyId;

    #[SerializedName('name')]
    public string $name;

    public function __construct(string $businessId, string $createdAt, string $id, string $licenseKeyId, string $name)
    {
        $this->businessId = $businessId;
        $this->createdAt = $createdAt;
        $this->id = $id;
        $this->licenseKeyId = $licenseKeyId;
        $this->name = $name;
    }
}
