<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class LicenseKeyDuration
{
    #[SerializedName('count')]
    public int $count;

    #[SerializedName('interval')]
    public TimeInterval $interval;

    public function __construct(int $count, TimeInterval $interval)
    {
        $this->count = $count;
        $this->interval = $interval;
    }
}
