<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

enum ListDisputesDisputeStage: string
{
    case PreDispute = 'pre_dispute';
    case Dispute = 'dispute';
    case PreArbitration = 'pre_arbitration';
}
