<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class ListWebhooksResponse
{
    /**
     * @var WebhookDetails[]
     * List of webhoooks
     */
    #[SerializedName('data')]
    public array $data;

    /**
     * true if no more values are to be fetched.
     */
    #[SerializedName('done')]
    public bool $done;

    /**
     * Cursor pointing to the next paginated object
     */
    #[SerializedName('iterator')]
    public ?string $iterator;

    /**
     * Cusror pointing to the previous previous object
     */
    #[SerializedName('prev_iterator')]
    public ?string $prevIterator;

    public function __construct(array $data, bool $done, ?string $iterator = null, ?string $prevIterator = null)
    {
        $this->data = $data;
        $this->done = $done;
        $this->iterator = $iterator;
        $this->prevIterator = $prevIterator;
    }
}
