<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

enum ListPaymentsHandlerStatus: string
{
    case Succeeded = 'succeeded';
    case Failed = 'failed';
    case Cancelled = 'cancelled';
    case Processing = 'processing';
    case RequiresCustomerAction = 'requires_customer_action';
    case RequiresMerchantAction = 'requires_merchant_action';
    case RequiresPaymentMethod = 'requires_payment_method';
    case RequiresConfirmation = 'requires_confirmation';
    case RequiresCapture = 'requires_capture';
    case PartiallyCaptured = 'partially_captured';
    case PartiallyCapturedAndCapturable = 'partially_captured_and_capturable';
}
