<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class ListBrandsResponse
{
    /**
     * @var BrandResponse[]
     * List of brands for this business
     */
    #[SerializedName('items')]
    public array $items;

    public function __construct(array $items)
    {
        $this->items = $items;
    }
}
