<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class MeterFilterCondition
{
    /**
     * Filter key to apply
     */
    #[SerializedName('key')]
    public string $key;

    #[SerializedName('operator')]
    public FilterOperator $operator;

    /**
     * Filter value
     */
    #[SerializedName('value')]
    public string $value;

    public function __construct(string $key, FilterOperator $operator, string $value)
    {
        $this->key = $key;
        $this->operator = $operator;
        $this->value = $value;
    }
}
