<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class MeterResponse
{
    #[SerializedName('aggregation_type')]
    public AggregationType $aggregationType;

    #[SerializedName('business_id')]
    public string $businessId;

    #[SerializedName('created_at')]
    public string $createdAt;

    #[SerializedName('description')]
    public ?string $description;

    #[SerializedName('event_type')]
    public string $eventType;

    #[SerializedName('event_value')]
    public ?string $eventValue;

    #[SerializedName('filter')]
    public ?MeterResponseFilter $filter;

    #[SerializedName('id')]
    public string $id;

    #[SerializedName('measurement_unit')]
    public string $measurementUnit;

    #[SerializedName('name')]
    public string $name;

    #[SerializedName('updated_at')]
    public string $updatedAt;

    public function __construct(
        AggregationType $aggregationType,
        string $businessId,
        string $createdAt,
        ?string $description = null,
        string $eventType,
        ?string $eventValue = null,
        ?MeterResponseFilter $filter = null,
        string $id,
        string $measurementUnit,
        string $name,
        string $updatedAt
    ) {
        $this->aggregationType = $aggregationType;
        $this->businessId = $businessId;
        $this->createdAt = $createdAt;
        $this->description = $description;
        $this->eventType = $eventType;
        $this->eventValue = $eventValue;
        $this->filter = $filter;
        $this->id = $id;
        $this->measurementUnit = $measurementUnit;
        $this->name = $name;
        $this->updatedAt = $updatedAt;
    }
}
