<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class MeterFilter
{
    #[SerializedName('clauses')]
    public FilterType $clauses;

    #[SerializedName('conjunction')]
    public Conjunction $conjunction;

    public function __construct(FilterType $clauses, Conjunction $conjunction)
    {
        $this->clauses = $clauses;
        $this->conjunction = $conjunction;
    }
}
