<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class NewCustomer
{
    #[SerializedName('email')]
    public string $email;

    #[SerializedName('name')]
    public string $name;

    #[SerializedName('phone_number')]
    public ?string $phoneNumber;

    public function __construct(string $email, string $name, ?string $phoneNumber = null)
    {
        $this->email = $email;
        $this->name = $name;
        $this->phoneNumber = $phoneNumber;
    }
}
