<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class OnDemandSubscriptionReq
{
    /**
     * If set as True, does not perform any charge and only authorizes payment method details for future use.
     */
    #[SerializedName('mandate_only')]
    public bool $mandateOnly;

    /**
	 * Product price for the initial charge to customer
If not specified the stored price of the product will be used
	 */
    #[SerializedName('product_price')]
    public ?int $productPrice;

    public function __construct(bool $mandateOnly, ?int $productPrice = null)
    {
        $this->mandateOnly = $mandateOnly;
        $this->productPrice = $productPrice;
    }
}
