<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

enum OneTimePriceType: string
{
    case OneTimePrice = 'one_time_price';
}
