<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class OneTimeProductCartItemReq
{
    /**
     * Amount the customer pays if pay_what_you_want is enabled. If disabled then amount will be ignored
     */
    #[SerializedName('amount')]
    public ?int $amount;

    #[SerializedName('product_id')]
    public string $productId;

    #[SerializedName('quantity')]
    public int $quantity;

    public function __construct(?int $amount = null, string $productId, int $quantity)
    {
        $this->amount = $amount;
        $this->productId = $productId;
        $this->quantity = $quantity;
    }
}
