<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

enum OutgoingWebhookData3PayloadType: string
{
    case Refund = 'Refund';
}
