<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

enum OutgoingWebhookData2PayloadType: string
{
    case Subscription = 'Subscription';
}
