<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class OutgoingWebhook
{
    #[SerializedName('business_id')]
    public string $businessId;

    #[SerializedName('data')]
    public OutgoingWebhookData $data;

    /**
     * The timestamp of when the event occurred (not necessarily the same of when it was delivered)
     */
    #[SerializedName('timestamp')]
    public string $timestamp;

    /**
     * Event types for Dodo events
     */
    #[SerializedName('type')]
    public EventType $type;

    public function __construct(string $businessId, OutgoingWebhookData $data, string $timestamp, EventType $type)
    {
        $this->businessId = $businessId;
        $this->data = $data;
        $this->timestamp = $timestamp;
        $this->type = $type;
    }
}
