<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class PartialRefundItem
{
    /**
     * The amount to refund. if None the whole item is refunded
     */
    #[SerializedName('amount')]
    public ?int $amount;

    /**
     * The id of the item (i.e. `product_id` or `addon_id`)
     */
    #[SerializedName('item_id')]
    public string $itemId;

    /**
     * Specify if tax is inclusive of the refund. Default true.
     */
    #[SerializedName('tax_inclusive')]
    public ?bool $taxInclusive;

    public function __construct(?int $amount = null, string $itemId, ?bool $taxInclusive = null)
    {
        $this->amount = $amount;
        $this->itemId = $itemId;
        $this->taxInclusive = $taxInclusive;
    }
}
