<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class PatchWebhookRequest
{
    /**
     * Description of the webhook
     */
    #[SerializedName('description')]
    public ?string $description;

    /**
     * To Disable the endpoint, set it to true.
     */
    #[SerializedName('disabled')]
    public ?bool $disabled;

    /**
	 * @var EventType[]|null
	 * Filter events to the endpoint.

Webhook event will only be sent for events in the list.
	 */
    #[SerializedName('filter_types')]
    public ?array $filterTypes;

    #[SerializedName('metadata')]
    public ?array $metadata;

    /**
     * Rate limit
     */
    #[SerializedName('rate_limit')]
    public ?int $rateLimit;

    /**
     * Url endpoint
     */
    #[SerializedName('url')]
    public ?string $url;

    public function __construct(
        ?string $description = null,
        ?bool $disabled = null,
        ?array $filterTypes = [],
        ?array $metadata = [],
        ?int $rateLimit = null,
        ?string $url = null
    ) {
        $this->description = $description;
        $this->disabled = $disabled;
        $this->filterTypes = $filterTypes;
        $this->metadata = $metadata;
        $this->rateLimit = $rateLimit;
        $this->url = $url;
    }
}
