<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class PatchCustomerRequest
{
    #[SerializedName('name')]
    public ?string $name;

    #[SerializedName('phone_number')]
    public ?string $phoneNumber;

    public function __construct(?string $name = null, ?string $phoneNumber = null)
    {
        $this->name = $name;
        $this->phoneNumber = $phoneNumber;
    }
}
