<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class PatchProductRequest
{
    /**
     * Description of the product, optional and must be at most 1000 characters.
     */
    #[SerializedName('description')]
    public ?string $description;

    /**
     * Product image id after its uploaded to S3
     */
    #[SerializedName('image_id')]
    public ?string $imageId;

    /**
	 * Message sent to the customer upon license key activation.

Only applicable if `license_key_enabled` is `true`. This message contains instructions for
activating the license key.
	 */
    #[SerializedName('license_key_activation_message')]
    public ?string $licenseKeyActivationMessage;

    /**
	 * Limit for the number of activations for the license key.

Only applicable if `license_key_enabled` is `true`. Represents the maximum number of times
the license key can be activated.
	 */
    #[SerializedName('license_key_activations_limit')]
    public ?int $licenseKeyActivationsLimit;

    #[SerializedName('license_key_duration')]
    public ?LicenseKeyDuration $licenseKeyDuration;

    /**
	 * Whether the product requires a license key.

If `true`, additional fields related to license key (duration, activations limit, activation message)
become applicable.
	 */
    #[SerializedName('license_key_enabled')]
    public ?bool $licenseKeyEnabled;

    /**
     * Name of the product, optional and must be at most 100 characters.
     */
    #[SerializedName('name')]
    public ?string $name;

    #[SerializedName('price')]
    public ?Price $price;

    /**
     * Represents the different categories of taxation applicable to various products and services.
     */
    #[SerializedName('tax_category')]
    public ?TaxCategory $taxCategory;

    public function __construct(
        ?string $description = null,
        ?string $imageId = null,
        ?string $licenseKeyActivationMessage = null,
        ?int $licenseKeyActivationsLimit = null,
        ?LicenseKeyDuration $licenseKeyDuration = null,
        ?bool $licenseKeyEnabled = null,
        ?string $name = null,
        ?Price $price = null,
        ?TaxCategory $taxCategory = null
    ) {
        $this->description = $description;
        $this->imageId = $imageId;
        $this->licenseKeyActivationMessage = $licenseKeyActivationMessage;
        $this->licenseKeyActivationsLimit = $licenseKeyActivationsLimit;
        $this->licenseKeyDuration = $licenseKeyDuration;
        $this->licenseKeyEnabled = $licenseKeyEnabled;
        $this->name = $name;
        $this->price = $price;
        $this->taxCategory = $taxCategory;
    }
}
