<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class PatchLicenseKeyRequest
{
    /**
	 * The updated activation limit for the license key.
Use `null` to remove the limit, or omit this field to leave it unchanged.
	 */
    #[SerializedName('activations_limit')]
    public ?int $activationsLimit;

    /**
	 * Indicates whether the license key should be disabled.
A value of `true` disables the key, while `false` enables it. Omit this field to leave it unchanged.
	 */
    #[SerializedName('disabled')]
    public ?bool $disabled;

    /**
	 * The updated expiration timestamp for the license key in UTC.
Use `null` to remove the expiration date, or omit this field to leave it unchanged.
	 */
    #[SerializedName('expires_at')]
    public ?string $expiresAt;

    public function __construct(?int $activationsLimit = null, ?bool $disabled = null, ?string $expiresAt = null)
    {
        $this->activationsLimit = $activationsLimit;
        $this->disabled = $disabled;
        $this->expiresAt = $expiresAt;
    }
}
