<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class PatchAddonRequest
{
    #[SerializedName('currency')]
    public ?Currency $currency;

    /**
     * Description of the Addon, optional and must be at most 1000 characters.
     */
    #[SerializedName('description')]
    public ?string $description;

    /**
     * Addon image id after its uploaded to S3
     */
    #[SerializedName('image_id')]
    public ?string $imageId;

    /**
     * Name of the Addon, optional and must be at most 100 characters.
     */
    #[SerializedName('name')]
    public ?string $name;

    /**
     * Amount of the addon
     */
    #[SerializedName('price')]
    public ?int $price;

    /**
     * Represents the different categories of taxation applicable to various products and services.
     */
    #[SerializedName('tax_category')]
    public ?TaxCategory $taxCategory;

    public function __construct(
        ?Currency $currency = null,
        ?string $description = null,
        ?string $imageId = null,
        ?string $name = null,
        ?int $price = null,
        ?TaxCategory $taxCategory = null
    ) {
        $this->currency = $currency;
        $this->description = $description;
        $this->imageId = $imageId;
        $this->name = $name;
        $this->price = $price;
        $this->taxCategory = $taxCategory;
    }
}
