<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class PatchDigitalProductDeliveryRequest
{
    /**
     * External URL to digital product
     */
    #[SerializedName('external_url')]
    public ?string $externalUrl;

    /**
     * @var string[]|null
     * Uploaded files ids of digital product
     */
    #[SerializedName('files')]
    public ?array $files;

    /**
     * Instructions to download and use the digital product
     */
    #[SerializedName('instructions')]
    public ?string $instructions;

    public function __construct(?string $externalUrl = null, ?array $files = [], ?string $instructions = null)
    {
        $this->externalUrl = $externalUrl;
        $this->files = $files;
        $this->instructions = $instructions;
    }
}
