<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class PatchSubscriptionRequest
{
    #[SerializedName('billing')]
    public ?Billing $billing;

    #[SerializedName('cancel_at_next_billing_date')]
    public ?bool $cancelAtNextBillingDate;

    #[SerializedName('disable_on_demand')]
    public ?DisableOnDemand $disableOnDemand;

    #[SerializedName('metadata')]
    public ?PatchSubscriptionRequestMetadata $metadata;

    #[SerializedName('status')]
    public ?PatchSubscriptionRequestStatus $status;

    #[SerializedName('tax_id')]
    public ?string $taxId;

    public function __construct(
        ?Billing $billing = null,
        ?bool $cancelAtNextBillingDate = null,
        ?DisableOnDemand $disableOnDemand = null,
        ?PatchSubscriptionRequestMetadata $metadata = null,
        ?PatchSubscriptionRequestStatus $status = null,
        ?string $taxId = null
    ) {
        $this->billing = $billing;
        $this->cancelAtNextBillingDate = $cancelAtNextBillingDate;
        $this->disableOnDemand = $disableOnDemand;
        $this->metadata = $metadata;
        $this->status = $status;
        $this->taxId = $taxId;
    }
}
