<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class PatchBrandRequest
{
    /**
     * The UUID you got back from the presigned‐upload call
     */
    #[SerializedName('image_id')]
    public ?string $imageId;

    #[SerializedName('name')]
    public ?string $name;

    #[SerializedName('statement_descriptor')]
    public ?string $statementDescriptor;

    #[SerializedName('support_email')]
    public ?string $supportEmail;

    public function __construct(
        ?string $imageId = null,
        ?string $name = null,
        ?string $statementDescriptor = null,
        ?string $supportEmail = null
    ) {
        $this->imageId = $imageId;
        $this->name = $name;
        $this->statementDescriptor = $statementDescriptor;
        $this->supportEmail = $supportEmail;
    }
}
