<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class PatchSubscriptionRequest
{
    #[SerializedName('billing')]
    public ?BillingAddress $billing;

    #[SerializedName('metadata')]
    public ?array $metadata;

    #[SerializedName('status')]
    public ?SubscriptionStatus $status;

    #[SerializedName('tax_id')]
    public ?string $taxId;

    public function __construct(
        ?BillingAddress $billing = null,
        ?array $metadata = [],
        ?SubscriptionStatus $status = null,
        ?string $taxId = null
    ) {
        $this->billing = $billing;
        $this->metadata = $metadata;
        $this->status = $status;
        $this->taxId = $taxId;
    }
}
