<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class PaymentLineItemsResponse
{
    #[SerializedName('currency')]
    public Currency $currency;

    /**
     * @var PaymentLineItem[]
     */
    #[SerializedName('items')]
    public array $items;

    public function __construct(Currency $currency, array $items)
    {
        $this->currency = $currency;
        $this->items = $items;
    }
}
