<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class Payment
{
    #[SerializedName('billing')]
    public BillingAddress $billing;

    /**
     * Identifier of the business associated with the payment
     */
    #[SerializedName('business_id')]
    public string $businessId;

    /**
     * ISO country code alpha2 variant
     */
    #[SerializedName('card_issuing_country')]
    public ?CountryCodeAlpha2 $cardIssuingCountry;

    /**
     * The last four digits of the card
     */
    #[SerializedName('card_last_four')]
    public ?string $cardLastFour;

    /**
     * Card network like VISA, MASTERCARD etc.
     */
    #[SerializedName('card_network')]
    public ?string $cardNetwork;

    /**
     * The type of card DEBIT or CREDIT
     */
    #[SerializedName('card_type')]
    public ?string $cardType;

    /**
     * Timestamp when the payment was created
     */
    #[SerializedName('created_at')]
    public string $createdAt;

    #[SerializedName('currency')]
    public Currency $currency;

    #[SerializedName('customer')]
    public CustomerLimitedDetailsResponse $customer;

    /**
     * The discount id if discount is applied
     */
    #[SerializedName('discount_id')]
    public ?string $discountId;

    /**
     * @var DisputeResponse[]
     * List of disputes associated with this payment
     */
    #[SerializedName('disputes')]
    public array $disputes;

    /**
     * An error message if the payment failed
     */
    #[SerializedName('error_message')]
    public ?string $errorMessage;

    #[SerializedName('metadata')]
    public array $metadata;

    /**
     * Unique identifier for the payment
     */
    #[SerializedName('payment_id')]
    public string $paymentId;

    /**
     * Checkout URL
     */
    #[SerializedName('payment_link')]
    public ?string $paymentLink;

    /**
     * Payment method used by customer (e.g. "card", "bank_transfer")
     */
    #[SerializedName('payment_method')]
    public ?string $paymentMethod;

    /**
     * Specific type of payment method (e.g. "visa", "mastercard")
     */
    #[SerializedName('payment_method_type')]
    public ?string $paymentMethodType;

    /**
     * @var OneTimeProductCartItemResponse[]|null
     * List of products purchased in a one-time payment
     */
    #[SerializedName('product_cart')]
    public ?array $productCart;

    /**
     * @var RefundResponse[]
     * List of refunds issued for this payment
     */
    #[SerializedName('refunds')]
    public array $refunds;

    /**
	 * The amount that will be credited to your Dodo balance after currency conversion and processing.
Especially relevant for adaptive pricing where the customer's payment currency differs from your settlement currency.
	 */
    #[SerializedName('settlement_amount')]
    public int $settlementAmount;

    #[SerializedName('settlement_currency')]
    public Currency $settlementCurrency;

    /**
	 * This represents the portion of settlement_amount that corresponds to taxes collected.
Especially relevant for adaptive pricing where the tax component must be tracked separately
in your Dodo balance.
	 */
    #[SerializedName('settlement_tax')]
    public ?int $settlementTax;

    #[SerializedName('status')]
    public ?IntentStatus $status;

    /**
     * Identifier of the subscription if payment is part of a subscription
     */
    #[SerializedName('subscription_id')]
    public ?string $subscriptionId;

    /**
     * Amount of tax collected in smallest currency unit (e.g. cents)
     */
    #[SerializedName('tax')]
    public ?int $tax;

    /**
     * Total amount charged to the customer including tax, in smallest currency unit (e.g. cents)
     */
    #[SerializedName('total_amount')]
    public int $totalAmount;

    /**
     * Timestamp when the payment was last updated
     */
    #[SerializedName('updated_at')]
    public ?string $updatedAt;

    #[SerializedName('payload_type')]
    public PaymentPayloadType $payloadType;

    public function __construct(
        BillingAddress $billing,
        string $businessId,
        ?CountryCodeAlpha2 $cardIssuingCountry = null,
        ?string $cardLastFour = null,
        ?string $cardNetwork = null,
        ?string $cardType = null,
        string $createdAt,
        Currency $currency,
        CustomerLimitedDetailsResponse $customer,
        ?string $discountId = null,
        array $disputes,
        ?string $errorMessage = null,
        array $metadata,
        string $paymentId,
        ?string $paymentLink = null,
        ?string $paymentMethod = null,
        ?string $paymentMethodType = null,
        ?array $productCart = [],
        array $refunds,
        int $settlementAmount,
        Currency $settlementCurrency,
        ?int $settlementTax = null,
        ?IntentStatus $status = null,
        ?string $subscriptionId = null,
        ?int $tax = null,
        int $totalAmount,
        ?string $updatedAt = null,
        PaymentPayloadType $payloadType
    ) {
        $this->billing = $billing;
        $this->businessId = $businessId;
        $this->cardIssuingCountry = $cardIssuingCountry;
        $this->cardLastFour = $cardLastFour;
        $this->cardNetwork = $cardNetwork;
        $this->cardType = $cardType;
        $this->createdAt = $createdAt;
        $this->currency = $currency;
        $this->customer = $customer;
        $this->discountId = $discountId;
        $this->disputes = $disputes;
        $this->errorMessage = $errorMessage;
        $this->metadata = $metadata;
        $this->paymentId = $paymentId;
        $this->paymentLink = $paymentLink;
        $this->paymentMethod = $paymentMethod;
        $this->paymentMethodType = $paymentMethodType;
        $this->productCart = $productCart;
        $this->refunds = $refunds;
        $this->settlementAmount = $settlementAmount;
        $this->settlementCurrency = $settlementCurrency;
        $this->settlementTax = $settlementTax;
        $this->status = $status;
        $this->subscriptionId = $subscriptionId;
        $this->tax = $tax;
        $this->totalAmount = $totalAmount;
        $this->updatedAt = $updatedAt;
        $this->payloadType = $payloadType;
    }
}
