<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class PaymentLineItem
{
    #[SerializedName('amount')]
    public int $amount;

    #[SerializedName('description')]
    public ?string $description;

    #[SerializedName('items_id')]
    public string $itemsId;

    #[SerializedName('name')]
    public ?string $name;

    #[SerializedName('refundable_amount')]
    public int $refundableAmount;

    #[SerializedName('tax')]
    public int $tax;

    public function __construct(
        int $amount,
        ?string $description = null,
        string $itemsId,
        ?string $name = null,
        int $refundableAmount,
        int $tax
    ) {
        $this->amount = $amount;
        $this->description = $description;
        $this->itemsId = $itemsId;
        $this->name = $name;
        $this->refundableAmount = $refundableAmount;
        $this->tax = $tax;
    }
}
