<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

enum PaymentMethodTypes: string
{
    case Credit = 'credit';
    case Debit = 'debit';
    case UpiCollect = 'upi_collect';
    case UpiIntent = 'upi_intent';
    case ApplePay = 'apple_pay';
    case Cashapp = 'cashapp';
    case GooglePay = 'google_pay';
    case Multibanco = 'multibanco';
    case BancontactCard = 'bancontact_card';
    case Eps = 'eps';
    case Ideal = 'ideal';
    case Przelewy24 = 'przelewy24';
    case Affirm = 'affirm';
    case Klarna = 'klarna';
    case Sepa = 'sepa';
    case Ach = 'ach';
    case AmazonPay = 'amazon_pay';
}
