<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

enum PayoutStatus: string
{
    case InProgress = 'in_progress';
    case Failed = 'failed';
    case Success = 'success';
}
