<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

enum PayoutStatus: string
{
    case NotInitiated = 'not_initiated';
    case InProgress = 'in_progress';
    case OnHold = 'on_hold';
    case Failed = 'failed';
    case Success = 'success';
}
