<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class ProductItemReq
{
    /**
     * @var AttachAddonReq[]|null
     * only valid if product is a subscription
     */
    #[SerializedName('addons')]
    public ?array $addons;

    /**
	 * Amount the customer pays if pay_what_you_want is enabled. If disabled then amount will be ignored
Represented in the lowest denomination of the currency (e.g., cents for USD).
For example, to charge $1.00, pass `100`.
Only applicable for one time payments
	 */
    #[SerializedName('amount')]
    public ?int $amount;

    /**
     * unique id of the product
     */
    #[SerializedName('product_id')]
    public string $productId;

    #[SerializedName('quantity')]
    public int $quantity;

    public function __construct(?array $addons = [], ?int $amount = null, string $productId, int $quantity)
    {
        $this->addons = $addons;
        $this->amount = $amount;
        $this->productId = $productId;
        $this->quantity = $quantity;
    }
}
