<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

enum ProrationBillingMode: string
{
    case ProratedImmediately = 'prorated_immediately';
    case FullImmediately = 'full_immediately';
    case DifferenceImmediately = 'difference_immediately';
}
