<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class SubscriptionData
{
    #[SerializedName('on_demand')]
    public ?SubscriptionDataOnDemand $onDemand;

    /**
     * Optional trial period in days If specified, this value overrides the trial period set in the product's price Must be between 0 and 10000 days
     */
    #[SerializedName('trial_period_days')]
    public ?int $trialPeriodDays;

    public function __construct(?SubscriptionDataOnDemand $onDemand = null, ?int $trialPeriodDays = null)
    {
        $this->onDemand = $onDemand;
        $this->trialPeriodDays = $trialPeriodDays;
    }
}
