<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

enum SubscriptionStatus: string
{
    case Pending = 'pending';
    case Active = 'active';
    case OnHold = 'on_hold';
    case Cancelled = 'cancelled';
    case Failed = 'failed';
    case Expired = 'expired';
}
