<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class Subscription
{
    /**
     * @var AddonCartResponseItem[]
     * Addons associated with this subscription
     */
    #[SerializedName('addons')]
    public array $addons;

    #[SerializedName('billing')]
    public BillingAddress $billing;

    /**
     * Indicates if the subscription will cancel at the next billing date
     */
    #[SerializedName('cancel_at_next_billing_date')]
    public bool $cancelAtNextBillingDate;

    /**
     * Cancelled timestamp if the subscription is cancelled
     */
    #[SerializedName('cancelled_at')]
    public ?string $cancelledAt;

    /**
     * Timestamp when the subscription was created
     */
    #[SerializedName('created_at')]
    public string $createdAt;

    #[SerializedName('currency')]
    public Currency $currency;

    #[SerializedName('customer')]
    public CustomerLimitedDetailsResponse $customer;

    /**
     * Number of remaining discount cycles if discount is applied
     */
    #[SerializedName('discount_cycles_remaining')]
    public ?int $discountCyclesRemaining;

    /**
     * The discount id if discount is applied
     */
    #[SerializedName('discount_id')]
    public ?string $discountId;

    #[SerializedName('metadata')]
    public array $metadata;

    /**
     * Timestamp of the next scheduled billing. Indicates the end of current billing period
     */
    #[SerializedName('next_billing_date')]
    public string $nextBillingDate;

    /**
     * Wether the subscription is on-demand or not
     */
    #[SerializedName('on_demand')]
    public bool $onDemand;

    /**
     * Number of payment frequency intervals
     */
    #[SerializedName('payment_frequency_count')]
    public int $paymentFrequencyCount;

    #[SerializedName('payment_frequency_interval')]
    public TimeInterval $paymentFrequencyInterval;

    /**
     * Timestamp of the last payment. Indicates the start of current billing period
     */
    #[SerializedName('previous_billing_date')]
    public string $previousBillingDate;

    /**
     * Identifier of the product associated with this subscription
     */
    #[SerializedName('product_id')]
    public string $productId;

    /**
     * Number of units/items included in the subscription
     */
    #[SerializedName('quantity')]
    public int $quantity;

    /**
     * Amount charged before tax for each recurring payment in smallest currency unit (e.g. cents)
     */
    #[SerializedName('recurring_pre_tax_amount')]
    public int $recurringPreTaxAmount;

    #[SerializedName('status')]
    public SubscriptionStatus $status;

    /**
     * Unique identifier for the subscription
     */
    #[SerializedName('subscription_id')]
    public string $subscriptionId;

    /**
     * Number of subscription period intervals
     */
    #[SerializedName('subscription_period_count')]
    public int $subscriptionPeriodCount;

    #[SerializedName('subscription_period_interval')]
    public TimeInterval $subscriptionPeriodInterval;

    /**
     * Indicates if the recurring_pre_tax_amount is tax inclusive
     */
    #[SerializedName('tax_inclusive')]
    public bool $taxInclusive;

    /**
     * Number of days in the trial period (0 if no trial)
     */
    #[SerializedName('trial_period_days')]
    public int $trialPeriodDays;

    #[SerializedName('payload_type')]
    public SubscriptionPayloadType $payloadType;

    public function __construct(
        array $addons,
        BillingAddress $billing,
        bool $cancelAtNextBillingDate,
        ?string $cancelledAt = null,
        string $createdAt,
        Currency $currency,
        CustomerLimitedDetailsResponse $customer,
        ?int $discountCyclesRemaining = null,
        ?string $discountId = null,
        array $metadata,
        string $nextBillingDate,
        bool $onDemand,
        int $paymentFrequencyCount,
        TimeInterval $paymentFrequencyInterval,
        string $previousBillingDate,
        string $productId,
        int $quantity,
        int $recurringPreTaxAmount,
        SubscriptionStatus $status,
        string $subscriptionId,
        int $subscriptionPeriodCount,
        TimeInterval $subscriptionPeriodInterval,
        bool $taxInclusive,
        int $trialPeriodDays,
        SubscriptionPayloadType $payloadType
    ) {
        $this->addons = $addons;
        $this->billing = $billing;
        $this->cancelAtNextBillingDate = $cancelAtNextBillingDate;
        $this->cancelledAt = $cancelledAt;
        $this->createdAt = $createdAt;
        $this->currency = $currency;
        $this->customer = $customer;
        $this->discountCyclesRemaining = $discountCyclesRemaining;
        $this->discountId = $discountId;
        $this->metadata = $metadata;
        $this->nextBillingDate = $nextBillingDate;
        $this->onDemand = $onDemand;
        $this->paymentFrequencyCount = $paymentFrequencyCount;
        $this->paymentFrequencyInterval = $paymentFrequencyInterval;
        $this->previousBillingDate = $previousBillingDate;
        $this->productId = $productId;
        $this->quantity = $quantity;
        $this->recurringPreTaxAmount = $recurringPreTaxAmount;
        $this->status = $status;
        $this->subscriptionId = $subscriptionId;
        $this->subscriptionPeriodCount = $subscriptionPeriodCount;
        $this->subscriptionPeriodInterval = $subscriptionPeriodInterval;
        $this->taxInclusive = $taxInclusive;
        $this->trialPeriodDays = $trialPeriodDays;
        $this->payloadType = $payloadType;
    }
}
