<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

/**
 * Represents the different categories of taxation applicable to various products and services.
 */
enum TaxCategory: string
{
    case DigitalProducts = 'digital_products';
    case Saas = 'saas';
    case EBook = 'e_book';
    case Edtech = 'edtech';
}
