<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class UpdateProductImageResponse
{
    #[SerializedName('url')]
    public string $url;

    public function __construct(string $url)
    {
        $this->url = $url;
    }
}
