<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class UpdateAddonImageResponse
{
    #[SerializedName('image_id')]
    public string $imageId;

    #[SerializedName('url')]
    public string $url;

    public function __construct(string $imageId, string $url)
    {
        $this->imageId = $imageId;
        $this->url = $url;
    }
}
