<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class UpdateSubscriptionPlanReq
{
    /**
	 * @var AttachAddonReq[]|null
	 * Addons for the new plan.
Note : Leaving this empty would remove any existing addons
	 */
    #[SerializedName('addons')]
    public ?array $addons;

    /**
     * Unique identifier of the product to subscribe to
     */
    #[SerializedName('product_id')]
    public string $productId;

    #[SerializedName('proration_billing_mode')]
    public ProrationBillingMode $prorationBillingMode;

    /**
     * Number of units to subscribe for. Must be at least 1.
     */
    #[SerializedName('quantity')]
    public int $quantity;

    public function __construct(
        ?array $addons = [],
        string $productId,
        ProrationBillingMode $prorationBillingMode,
        int $quantity
    ) {
        $this->addons = $addons;
        $this->productId = $productId;
        $this->prorationBillingMode = $prorationBillingMode;
        $this->quantity = $quantity;
    }
}
