<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class UpdateBrandImageResponse
{
    /**
     * UUID that will be used as the image identifier/key suffix
     */
    #[SerializedName('image_id')]
    public string $imageId;

    /**
     * Presigned URL to upload the image
     */
    #[SerializedName('url')]
    public string $url;

    public function __construct(string $imageId, string $url)
    {
        $this->imageId = $imageId;
        $this->url = $url;
    }
}
