<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class UploadProductFile
{
    #[SerializedName('file_name')]
    public string $fileName;

    public function __construct(string $fileName)
    {
        $this->fileName = $fileName;
    }
}
