<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class ValidateLicenseKeyResponse
{
    #[SerializedName('valid')]
    public bool $valid;

    public function __construct(bool $valid)
    {
        $this->valid = $valid;
    }
}
