<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class WebhookHeadersReq
{
    #[SerializedName('headers')]
    public array $headers;

    public function __construct(array $headers)
    {
        $this->headers = $headers;
    }
}
