<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class WebhookEventLogResponse
{
    #[SerializedName('business_id')]
    public string $businessId;

    #[SerializedName('created_at')]
    public string $createdAt;

    #[SerializedName('event_id')]
    public string $eventId;

    #[SerializedName('event_type')]
    public string $eventType;

    #[SerializedName('latest_attempted_at')]
    public ?string $latestAttemptedAt;

    #[SerializedName('object_id')]
    public string $objectId;

    #[SerializedName('request')]
    public ?string $request;

    #[SerializedName('response')]
    public ?string $response;

    public function __construct(
        string $businessId,
        string $createdAt,
        string $eventId,
        string $eventType,
        ?string $latestAttemptedAt = null,
        string $objectId,
        ?string $request = null,
        ?string $response = null
    ) {
        $this->businessId = $businessId;
        $this->createdAt = $createdAt;
        $this->eventId = $eventId;
        $this->eventType = $eventType;
        $this->latestAttemptedAt = $latestAttemptedAt;
        $this->objectId = $objectId;
        $this->request = $request;
        $this->response = $response;
    }
}
