<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments\Models;

use Symfony\Component\Serializer\Annotation\SerializedName;

class WebhookDetails
{
    /**
     * Created at timestamp
     */
    #[SerializedName('created_at')]
    public string $createdAt;

    /**
     * An example webhook name.
     */
    #[SerializedName('description')]
    public string $description;

    /**
	 * Status of the webhook.

If true, events are not sent
	 */
    #[SerializedName('disabled')]
    public ?bool $disabled;

    /**
	 * @var string[]|null
	 * Filter events to the webhook.

Webhook event will only be sent for events in the list.
	 */
    #[SerializedName('filter_types')]
    public ?array $filterTypes;

    /**
     * The webhook's ID.
     */
    #[SerializedName('id')]
    public string $id;

    #[SerializedName('metadata')]
    public array $metadata;

    /**
     * Configured rate limit
     */
    #[SerializedName('rate_limit')]
    public ?int $rateLimit;

    /**
     * Updated at timestamp
     */
    #[SerializedName('updated_at')]
    public string $updatedAt;

    /**
     * Url endpoint of the webhook
     */
    #[SerializedName('url')]
    public string $url;

    public function __construct(
        string $createdAt,
        string $description,
        ?bool $disabled = null,
        ?array $filterTypes = [],
        string $id,
        array $metadata,
        ?int $rateLimit = null,
        string $updatedAt,
        string $url
    ) {
        $this->createdAt = $createdAt;
        $this->description = $description;
        $this->disabled = $disabled;
        $this->filterTypes = $filterTypes;
        $this->id = $id;
        $this->metadata = $metadata;
        $this->rateLimit = $rateLimit;
        $this->updatedAt = $updatedAt;
        $this->url = $url;
    }
}
