<?php

// This file was generated by liblab | https://liblab.com/

declare(strict_types=1);

namespace Dodopayments;

use Dodopayments\Services;

class Client
{
    public $addons;
    public $checkout;
    public $customers;
    public $discounts;
    public $disputes;
    public $invoices;
    public $licenseKeys;
    public $licenses;
    public $payments;
    public $payouts;
    public $products;
    public $refunds;
    public $subscriptions;
    public $webhookEvents;
    public $outgoingWebhooks;

    public function __construct(
        string $accessToken,
        string $tokenPrefix = 'Bearer ',
        string $environment = Environment::Default,
        float $timeout = 0
    ) {
        $this->addons = new Services\Addons($accessToken, $tokenPrefix, $environment, $timeout);
        $this->checkout = new Services\Checkout($accessToken, $tokenPrefix, $environment, $timeout);
        $this->customers = new Services\Customers($accessToken, $tokenPrefix, $environment, $timeout);
        $this->discounts = new Services\Discounts($accessToken, $tokenPrefix, $environment, $timeout);
        $this->disputes = new Services\Disputes($accessToken, $tokenPrefix, $environment, $timeout);
        $this->invoices = new Services\Invoices($accessToken, $tokenPrefix, $environment, $timeout);
        $this->licenseKeys = new Services\LicenseKeys($accessToken, $tokenPrefix, $environment, $timeout);
        $this->licenses = new Services\Licenses($accessToken, $tokenPrefix, $environment, $timeout);
        $this->payments = new Services\Payments($accessToken, $tokenPrefix, $environment, $timeout);
        $this->payouts = new Services\Payouts($accessToken, $tokenPrefix, $environment, $timeout);
        $this->products = new Services\Products($accessToken, $tokenPrefix, $environment, $timeout);
        $this->refunds = new Services\Refunds($accessToken, $tokenPrefix, $environment, $timeout);
        $this->subscriptions = new Services\Subscriptions($accessToken, $tokenPrefix, $environment, $timeout);
        $this->webhookEvents = new Services\WebhookEvents($accessToken, $tokenPrefix, $environment, $timeout);
        $this->outgoingWebhooks = new Services\OutgoingWebhooks($accessToken, $tokenPrefix, $environment, $timeout);
    }

    public function setBaseUrl(string $url)
    {
        $this->addons->setBaseUrl($url);
        $this->checkout->setBaseUrl($url);
        $this->customers->setBaseUrl($url);
        $this->discounts->setBaseUrl($url);
        $this->disputes->setBaseUrl($url);
        $this->invoices->setBaseUrl($url);
        $this->licenseKeys->setBaseUrl($url);
        $this->licenses->setBaseUrl($url);
        $this->payments->setBaseUrl($url);
        $this->payouts->setBaseUrl($url);
        $this->products->setBaseUrl($url);
        $this->refunds->setBaseUrl($url);
        $this->subscriptions->setBaseUrl($url);
        $this->webhookEvents->setBaseUrl($url);
        $this->outgoingWebhooks->setBaseUrl($url);
    }

    public function setAccessToken(string $accessToken)
    {
        $this->addons->setAccessToken($accessToken);
        $this->checkout->setAccessToken($accessToken);
        $this->customers->setAccessToken($accessToken);
        $this->discounts->setAccessToken($accessToken);
        $this->disputes->setAccessToken($accessToken);
        $this->invoices->setAccessToken($accessToken);
        $this->licenseKeys->setAccessToken($accessToken);
        $this->licenses->setAccessToken($accessToken);
        $this->payments->setAccessToken($accessToken);
        $this->payouts->setAccessToken($accessToken);
        $this->products->setAccessToken($accessToken);
        $this->refunds->setAccessToken($accessToken);
        $this->subscriptions->setAccessToken($accessToken);
        $this->webhookEvents->setAccessToken($accessToken);
        $this->outgoingWebhooks->setAccessToken($accessToken);
    }
}

// c029837e0e474b76bc487506e8799df5e3335891efe4fb02bda7a1441840310c
