<?php

// This file was generated by liblab | https://liblab.com/

namespace Dodopayments;

class Environment
{
    const Default = 'https://live.dodopayments.com';
    const LiveMode = 'https://live.dodopayments.com';
    const TestMode = 'https://test.dodopayments.com';
}
